from setuptools import setup, find_packages

setup(
    name="lora_trainer",
    version="2.0.0",
    description="Universal & Optimized Image LoRA Training Suite for Google Colab (SDXL, Pony, Illustrious, SD1.5, SD3.5, FLUX.1/2 Klein, Qwen, Z-Image, Krea)",
    author="Nguyen Duc Vuong",
    license="MIT",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1.0",
        "transformers>=4.40.0",
        "accelerate>=0.28.0",
        "safetensors>=0.4.2",
        "toml>=0.10.2",
        "pyyaml>=6.0",
        "pillow>=10.0.0",
        "requests>=2.31.0",
        "tqdm>=4.66.0",
        "voluptuous>=0.13.0",
        "imagesize>=1.4.1",
        "einops>=0.7.0",
        "ftfy>=6.1.1",
        "regex>=2023.10.3",
        "sentencepiece>=0.1.99",
        "protobuf>=3.20.0",
        "scipy>=1.11.0",
        "wandb>=0.16.0",
        "opencv-python-headless>=4.8.0",
        "diffusers>=0.28.0",
        "albumentations>=1.4.0",
        "lion-pytorch>=0.1.2",
        "prodigyopt>=1.0.0",
        "open_clip_torch>=2.24.0",
        "timm>=0.9.0",
        "google-genai>=0.1.1",
        "openai>=1.12.0",
        "bitsandbytes>=0.43.0",
        "optimum-quanto>=0.2.0",
        "python-dotenv>=1.0.0",
        "av>=11.0.0",
        "easydict>=1.13",
    ],
)
